# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d61251986afd685fc6ebce90f26f163987e1aec9502bb176d1c9ffbe227cb3c7da49a08a9bd24a30466f2c359e9ecd9e9c302fa83b31ab92f47a9695f5b44e7f

test:
  secret_key_base: 7ba46bbdc7f3c14127835b1fc7bfecddaec53eab844810ea6b6bf6322e77ef7429716d7c7e8fe88941a861a331c6f64941fdf3770e8304f90504e3605c70410d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
